### ISSUE TITLE
Linux AppImage 在Ubuntu 20.04上无法运行

### ISSUE THREAD

**Issue by whdxnty** [1zilc/fishing-funds#351]
### BUG 截图

$ chmod +x Fishing-Funds-5.4.1.AppImage
$ ./Fishing-Funds-5.4.1.AppImage 
[2850578:0117/151637.735436:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
15:16:40.630 › Checking for update
15:16:40.634 › returnData.checking
15:16:40.634 › menubar:  TypeError: Cannot read properties of undefined (reading 'hide')
    at t.<anonymous> (/tmp/.mount_FishinRZME5W/resources/app.asar/dist/main/main.js:14:546652)
    at t.emit (node:events:394:28)
    at t.<anonymous> (/tmp/.mount_FishinRZME5W/resources/app.asar/dist/main/main.js:14:394577)
    at /tmp/.mount_FishinRZME5W/resources/app.asar/dist/main/main.js:14:389405
    at Object.next (/tmp/.mount_FishinRZME5W/resources/app.asar/dist/main/main.js:14:389510)
    at s (/tmp/.mount_FishinRZME5W/resources/app.asar/dist/main/main.js:14:388224)
15:16:41.164 › Update for version 5.4.1 is not available (latest version: 5.4.1, downgrade is disallowed).

**Comment by 1zilc** [comment]
状态栏有看到一个带F的图标吗？

**Comment by whdxnty** [comment]
没有，因为这些报错信息显示后，根本打不开图形界面。

**Comment by whdxnty** [comment]
这个修改可以再上传一个APPImage吗？“修复非mac平台dock判断报错”。谢谢~

**Comment by 1zilc** [comment]
这个错误是不会影响启动的
![image](https://user-images.githubusercontent.com/44715458/149869548-55d70b69-b756-4c89-890a-2272b12dfeb7.png)

**Comment by whdxnty** [comment]
刚刚发现可以了，双击启动就好了，谢谢！
