### ISSUE TITLE
运行时报错globalShortcut cannot be used before the app is ready

### ISSUE THREAD

**Issue by ytrug1224** [1zilc/fishing-funds#552]
### 操作系统平台及版本号
mac

### BUG 截图

The DLL files are missing. Sit back while we build them for you with "npm run build-dll"
...

[electronmon] waiting for a change to restart it
/Users/zxj/GitHub/fishing-funds/src/main/main.ts:319
  globalShortcut.unregisterAll();
                 ^

Error: globalShortcut cannot be used before the app is ready
    at App.<anonymous> (/Users/zxj/GitHub/fishing-funds/src/main/main.ts:319:18)
    at App.emit (node:events:513:28)
    at lockSingleInstance (/Users/zxj/GitHub/fishing-funds/src/main/util.ts:31:9)
    at init (/Users/zxj/GitHub/fishing-funds/src/main/main.ts:44:3)
    at <anonymous> (/Users/zxj/GitHub/fishing-funds/src/main/main.ts:321:1)
    at Object.<anonymous> (/Users/zxj/GitHub/fishing-funds/src/main/main.ts:321:25)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.T (/Users/zxj/GitHub/fishing-funds/node_modules/_@esbuild-kit_cjs-loader@2.4.1@@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)

**Comment by 1zilc** [comment]
无法复线
